### ISSUE TITLE
Crash if no font is set

### ISSUE THREAD

**Issue by intrications** [itzikBraun/TutorialView#11]
If no font is set then the library crashes:

```
                    E  java.lang.NullPointerException
                     E      at android.graphics.FontFamily.nAddFontFromAsset(Native Method)
                     E      at android.graphics.FontFamily.addFontFromAsset(FontFamily.java:70)
                     E      at android.graphics.Typeface.createFromAsset(Typeface.java:185)
                     E      at com.braunster.tutorialview.view.AbstractTutorialView.initTypeFace(AbstractTutorialView.java:466)
                     E      at com.braunster.tutorialview.view.AbstractTutorialView.setTutorial(AbstractTutorialView.java:285)
                     E      at com.braunster.tutorialview.view.TutorialLayout.setTutorial(TutorialLayout.java:81)
                     E      at com.braunster.tutorialview.TutorialActivity.onWindowFocusChanged(TutorialActivity.java:110)
                     E      at com.android.internal.policy.impl.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:3174)
                     E      at android.view.View.dispatchWindowFocusChanged(View.java:8680)
                     E      at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1055)
                     E      at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3284)
                     E      at android.os.Handler.dispatchMessage(Handler.java:102)
                     E      at android.os.Looper.loop(Looper.java:135)
                     E      at android.app.ActivityThread.main(ActivityThread.java:5254)
                     E      at java.lang.reflect.Method.invoke(Native Method)
                     E      at java.lang.reflect.Method.invoke(Method.java:372)
                     E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                     E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
            Process  I  Sending signal. PID: 8443 SIG: 9
```

**Comment by itzikBraun** [comment]
Thank Michael, 

I will take a look today or tomorrow and fixit. Were you able to work with the library despite the issue?

**Comment by itzikBraun** [comment]
Can you checkout the project again and let me know for sure that you don't have this problem anymore?

**Comment by intrications** [comment]
@itzikBraun 

That hasn't fixed it. Now the sample app is crashing. All you seem to have done in the commit is not set the typeface and hence cause the Null Pointer Exception.

Is there more code that you meant to push?

**Comment by itzikBraun** [comment]
Yeah there was more code that was supposed to be there, Sorry about that. I will push it again.

**Comment by intrications** [comment]
@itzikBraun Are you able to push the full code?

**Comment by itzikBraun** [comment]
@intrications sorry it took so much time, I kind forgot about it.

Let me know if it works for you.
