### ISSUE TITLE
Is tutorial view creating a walk through from many Tutorials support?

### ISSUE THREAD

**Issue by progfiles** [itzikBraun/TutorialView#3]
Now it is not work. Can you provide example tutorial list pls?
Thanks!

**Comment by itzikBraun** [comment]
Hi, 

Did you tried the example from the app READE file?

```
ArrayList<Tutorial> tutorials = new ArrayList<>();
tutorials.add(tutorial);
tutorials.add(tutorial2);
tutorials.add(tutorial3);
tutorials.add(tutorial4);

builder.skipTutorialOnBackPressed(true);

builder.setWalkThroughList(tutorials);

// Starting the activity with an intent from the builder.
startActivity(builder.getIntent());
overridePendingTransition(R.anim.dummy, R.anim.dummy);
```

**Comment by nurcahyo** [comment]
Got an error exception "java.lang.IllegalArgumentException: You must pass at least on Tutorial object to the intent builder."

then when i pass tutorial object with builder.setTutorial(tutorial1) activity launched with transparent layout and i can't click anything,

**Comment by itzikBraun** [comment]
Can you share with me the code of how you launch the TutorialActivity?
If you don't want to share your code here you can send me an email at itzik.braun@gmail.com

If you launch it in onCreate or something similar it may won't work as the view you want to surround does not have any position yet. If this is the case try post it so it would run after the view position was calculated.

```
 view.post(new Runnable() {
            @Override
            public void run() {
                // Do your stuff here
            }
        });
```

**Comment by nurcahyo** [comment]
Still doesn't work.

Sorry, I can't share my code but I can reproduce this issue on test project mainactivity file.
just add this following lines in last onCreate method line on MainActivity.java

``` java
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Tutorial t1 = getBasicBuilderForTest(findViewById(R.id.view_bottom_left)).build();
                Tutorial t2 = getBasicBuilderForTest(findViewById(R.id.view_top_right)).build();
                Tutorial t3 = getBasicBuilderForTest(findViewById(R.id.view_almost_top_right)).build();
                Tutorial t4 = getBasicBuilderForTest(findViewById(R.id.view_top_left)).build();
                Tutorial t5 = getBasicBuilderForTest(findViewById(R.id.view_center)).build();


                TutorialIntentBuilder builder = new TutorialIntentBuilder(MainActivity.this);
//                builder.setTutorial(t1);
                builder.setWalkThroughList(new Tutorial[]{t1, t2, t3, t4, t5});
                startActivity(builder.getIntent());

                // Override the default animation of the entering activity.
                // This will allow the nice wrapping of the view by the tutorial activity.
                overridePendingTransition(R.anim.dummy, R.anim.dummy);
            }
        });
```

**Comment by itzikBraun** [comment]
I've pushed a new commit that suppose to fix the errors, Can you try it out and let me know if it's working for you?

Also, you should not use the runOnUIThread, You should try something like this:

```
  getWindow().getDecorView().post(new Runnable() {
            @Override
            public void run() {

                Tutorial t1 = getBasicBuilderForTest(findViewById(R.id.view_bottom_left))
                        .setTutorialInfoTextPosition(Tutorial.InfoPosition.ABOVE)
                        .setTutorialGotItPosition(Tutorial.GotItPosition.BOTTOM)
                        .build();

                Tutorial t2 = getBasicBuilderForTest(findViewById(R.id.view_top_right))
                        .setTutorialInfoTextPosition(Tutorial.InfoPosition.LEFT_OF)
                        .build();

                Tutorial t3 = getBasicBuilderForTest(findViewById(R.id.view_almost_top_right))
                        .setTutorialInfoTextPosition(Tutorial.InfoPosition.RIGHT_OF)
                        .build();

                Tutorial t4 = getBasicBuilderForTest(findViewById(R.id.view_top_left))
                        .setTutorialInfoTextPosition(Tutorial.InfoPosition.BELOW)
                        .build();

                Tutorial t5 = getBasicBuilderForTest(findViewById(R.id.view_center))
                        .setTutorialInfoTextPosition(Tutorial.InfoPosition.BELOW)
                        .setTutorialGotItPosition(Tutorial.GotItPosition.BOTTOM)
                        .build();


                TutorialIntentBuilder builder = new TutorialIntentBuilder(MainActivity.this);

                builder.setWalkThroughList(t1, t2, t3, t4, t5);
                startActivity(builder.getIntent());

                // Override the default animation of the entering activity.
                // This will allow the nice wrapping of the view by the tutorial activity.
                overridePendingTransition(R.anim.dummy, R.anim.dummy);
            }
        });
```

This code is now in the MainActivity of the app module so you don't need to copy it.

**Comment by nurcahyo** [comment]
It works but triggered another issue. 
1. Some tutorial info text & "got it" text visibility gone.
2. Thrown an exception when orientation changed:

``` java
05-04 07:16:38.598  17626-17626/com.bixbox E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
            at java.util.ArrayList.get(ArrayList.java:304)
            at com.braunster.tutorialview.TutorialActivity.onWindowFocusChanged(TutorialActivity.java:94)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onWindowFocusChanged(PhoneWindow.java:2642)
            at android.view.View.dispatchWindowFocusChanged(View.java:7564)
            at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:938)
            at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3009)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4895)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by itzikBraun** [comment]
I will test the orientation change, Can you tell me on which device you tested it on? Also with which tutorial the "GotIt" button was invisible?

**Comment by itzikBraun** [comment]
I have pushed a new commit, The TutorialActivity orientation is now locked to the orientation that was when the Activity is opened.

**Comment by itzikBraun** [comment]
No response.

**Comment by nurcahyo** [comment]
@itzikBraun sorry for late response, yes I am lock orientation too to handle that issue.
